GET http://localhost:3333/users HTTP/1.1

###

GET http://localhost:3333/users/54d535ef-5ecf-4685-aa52-2bd2d330d0c7 HTTP/1.1

###

POST http://localhost:3333/users HTTP/1.1
content-type: application/json

{
    "name": "Billie Jean",
    "email": "billie.jean@gmail.com"
}

###

POST http://localhost:3333/todos HTTP/1.1
content-type: application/json
x-user-id: 56732dfd-4ee4-4c57-b760-e26215dc44bb

{
    "title": "Task #6",
    "description": ""
}

###

POST http://localhost:3333/checkout HTTP/1.1
content-type: application/json
x-user-id: 56732dfd-4ee4-4c57-b760-e26215dc44bb