version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=micro-saas-with-bun
    volumes:
      - micro-saas-with-bun:/bitnami/postgresql

volumes:
  micro-saas-with-bun: